[project]
name = "pandas-experimentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.2",
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]